version: "3"

services:
  app:
    build: .
    command: npm start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file: .env
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:3.0